use std::fmt::{self, Write};

use super::MAX_BODY_SIZE_BYTES;

/// Renderer for the legacy publication orchestration.
///
/// That orchestration cannot supply validated literal first-parent history,
/// so it retains its original inputs instead of using the exact publisher's
/// bounded renderer.
pub(in crate::pre_push) struct PrBody<'a> {
    pub commit_body: &'a str,
    pub repo_url: &'a str,
    pub repo_fetch_url: &'a str,
    pub public_branch: Option<&'a str>,
    pub stack_pr_numbers: &'a [u64],
    pub current_pr_number: u64,
    pub latest_version: usize,
    pub base_branch: &'a str,
    pub gherrit_id: &'a str,
}

#[derive(Clone, Copy)]
enum HistoryTableFormat {
    Full,
    Sparse,
}

impl PrBody<'_> {
    pub fn render(&self) -> String {
        let format = if self.rendered_len(HistoryTableFormat::Full) > MAX_BODY_SIZE_BYTES {
            HistoryTableFormat::Sparse
        } else {
            HistoryTableFormat::Full
        };

        self.render_with_history(format)
    }

    fn rendered_len(&self, format: HistoryTableFormat) -> usize {
        let mut size = ByteCounter(0);
        self.write(&mut size, format).expect("counting rendered PR body bytes cannot fail");
        size.0
    }

    fn render_with_history(&self, format: HistoryTableFormat) -> String {
        let mut body = String::new();
        self.write(&mut body, format).expect("writing a PR body to a string cannot fail");
        body
    }

    fn write(&self, mut output: impl Write, history_format: HistoryTableFormat) -> fmt::Result {
        output.write_str(
            "<!-- WARNING: This PR description is automatically generated by GHerrit. Any manual edits will be overwritten on the next push. -->\n\n",
        )?;
        output.write_str(self.commit_body)?;
        output.write_str("\n\n---\n\n")?;
        self.write_navigation(&mut output)?;
        self.write_history_table(&mut output, history_format)?;
        self.write_download_section(&mut output)?;
        output.write_str("\n\n")?;
        output.write_str("*Stacked PRs enabled by [GHerrit](https://github.com/joshlf/gherrit).*")
    }

    fn write_navigation(&self, mut output: impl Write) -> fmt::Result {
        if let Some(branch) = self.public_branch {
            writeln!(output, "This PR is on branch [{branch}](../tree/{branch}).\n")?;
        }

        self.stack_pr_numbers.iter().rev().try_for_each(|number| {
            let prefix =
                if *number == self.current_pr_number { "👉" } else { "\u{3000}\u{2009}" };
            writeln!(output, "- {prefix} #{number}")
        })
    }

    fn write_history_table(
        &self,
        mut output: impl Write,
        format: HistoryTableFormat,
    ) -> fmt::Result {
        if self.latest_version <= 1 || self.repo_url.is_empty() {
            return Ok(());
        }

        write!(
            output,
            "\n\n**Latest Update:** v{} — [Compare vs v{}]({}/compare/gherrit/{}/v{}..gherrit/{}/v{})\n\n",
            self.latest_version,
            self.latest_version - 1,
            self.repo_url,
            self.gherrit_id,
            self.latest_version - 1,
            self.gherrit_id,
            self.latest_version
        )?;

        output.write_str(
            "<details>\n<summary><strong>📚 Full Patch History</strong></summary>\n\n",
        )?;
        output.write_str(
            "*Links show the diff between the row version and the column version.*\n\n",
        )?;

        output.write_str("|Version|")?;
        for version in (1..self.latest_version).rev() {
            write!(output, " v{version} |")?;
        }
        output.write_str("Base|")?;

        output.write_str("\n|:---|")?;
        for _ in 1..self.latest_version {
            output.write_str(":---|")?;
        }
        output.write_str(":---|\n")?;

        let prefix = if self.latest_version <= 8 { "vs " } else { "" };

        for row in (1..=self.latest_version).rev() {
            write!(output, "|v{row}|")?;

            for column in (1..self.latest_version).rev() {
                if column >= row {
                    output.write_str("|")?;
                    continue;
                }

                let show_link = match format {
                    HistoryTableFormat::Full => true,
                    HistoryTableFormat::Sparse => row == self.latest_version || row == column + 1,
                };

                if show_link {
                    write!(
                        output,
                        "[{prefix}v{column}]({}/compare/gherrit/{}/v{column}..gherrit/{}/v{row})|",
                        self.repo_url, self.gherrit_id, self.gherrit_id
                    )?;
                } else {
                    output.write_str("|")?;
                }
            }

            writeln!(
                output,
                "[{prefix}Base]({}/compare/{}..gherrit/{}/v{row})|",
                self.repo_url, self.base_branch, self.gherrit_id
            )?;
        }

        output.write_str("\n</details>")
    }

    fn write_download_section(&self, mut output: impl Write) -> fmt::Result {
        output.write_str(
            "\n<details>\n<summary><strong>⬇️ Download this PR</strong></summary>\n\n",
        )?;
        output.write_str("######\n\n")?;

        // While `git fetch origin {id}` would work most of the time, we use
        // the full `refs/heads/` syntax to avoid ambiguity with tags of the
        // same name.
        let id = self.gherrit_id;
        let repository = self.repo_fetch_url;
        let fetch = format!("git fetch {repository} refs/heads/{id}");
        let commands = [
            ("Branch", format!("{fetch} && git checkout -b pr-{id} FETCH_HEAD")),
            ("Checkout", format!("{fetch} && git checkout FETCH_HEAD")),
            ("Cherry Pick", format!("{fetch} && git cherry-pick FETCH_HEAD")),
            ("Pull", format!("git pull {repository} refs/heads/{id}")),
        ];

        commands.into_iter().try_for_each(|(title, command)| {
            writeln!(output, "**{title}**\n```bash\n{command}\n```\n")
        })?;

        output.write_str("</details>")
    }
}

struct ByteCounter(usize);

impl Write for ByteCounter {
    fn write_str(&mut self, value: &str) -> fmt::Result {
        self.0 += value.len();
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const STACK: &[u64] = &[11, 22, 33];

    fn body<'a>(
        commit_body: &'a str,
        public_branch: Option<&'a str>,
        current_pr_number: u64,
        latest_version: usize,
        gherrit_id: &'a str,
        base_branch: &'a str,
    ) -> PrBody<'a> {
        PrBody {
            commit_body,
            repo_url: "/octo/widgets",
            repo_fetch_url: "https://github.com/octo/widgets.git",
            public_branch,
            stack_pr_numbers: STACK,
            current_pr_number,
            latest_version,
            base_branch,
            gherrit_id,
        }
    }

    #[test]
    fn renders_private_root_at_v1() {
        insta::assert_snapshot!(
            body(
                "Introduce widgets\n\nExplain why the widgets matter.\n\n",
                None,
                11,
                1,
                "Groot",
                "main",
            )
            .render()
        );
    }

    #[test]
    fn renders_public_middle_at_v2_with_unicode() {
        insta::assert_snapshot!(body(
            "Render 雪 correctly ☃️\n\nKeep `code`, [links](https://example.com/?a=1&b=2), and <tags>.\n\n",
            Some("feature/雪-and-markdown"),
            22,
            2,
            "Gmiddle",
            "Groot",
        )
        .render());
    }

    #[test]
    fn renders_full_patch_history() {
        insta::assert_snapshot!(
            body("Finish the stack\n\n", None, 33, 4, "Gtip", "Gmiddle").render()
        );
    }

    #[test]
    fn renders_sparse_patch_history() {
        let body = body("", None, 22, 6, "Gmiddle", "Groot");
        insta::assert_snapshot!(body.render_with_history(HistoryTableFormat::Sparse));
    }

    #[test]
    fn metadata_like_text_is_ordinary_commit_body_content() {
        let commit_body = "Keep <!-- gherrit-meta: ordinary commit text --> exactly.";
        let rendered = body(commit_body, None, 22, 1, "Gmiddle", "Groot").render();

        assert!(rendered.contains(commit_body));
        assert_eq!(rendered.matches("gherrit-meta").count(), 1);
    }

    #[test]
    fn switches_to_sparse_history_only_above_the_size_limit() {
        let empty = body("", None, 22, 4, "Gmiddle", "Groot");
        let fixed_size = empty.rendered_len(HistoryTableFormat::Full);
        assert!(fixed_size < MAX_BODY_SIZE_BYTES);

        let exact_padding = "x".repeat(MAX_BODY_SIZE_BYTES - fixed_size);
        let exact = body(&exact_padding, None, 22, 4, "Gmiddle", "Groot").render();
        let omitted_in_sparse = "/compare/gherrit/Gmiddle/v1..gherrit/Gmiddle/v3";
        assert_eq!(exact.len(), MAX_BODY_SIZE_BYTES);
        assert!(exact.contains(omitted_in_sparse));

        let over_padding = format!("{exact_padding}x");
        let over = body(&over_padding, None, 22, 4, "Gmiddle", "Groot").render();
        assert!(!over.contains(omitted_in_sparse));
    }
}
