name: GHerrit – Rebase Stack
description: 'Automatically rebase the next PR in a GHerrit stack.'
inputs:
  token:
    description: '`GITHUB_TOKEN` to allow rebase and push'
    required: true
  pr_body:
    description: 'The body/description of the PR that was just merged. Used to extract the child PR ID from the GHerrit metadata.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        GH_TOKEN: ${{ inputs.token }}
        MERGED_PR_BODY: ${{ inputs.pr_body }}
      run: bash "$ACTION_PATH/ci/rebase_stack_child.sh"
