name: GHerrit – Rebase Stack
description: 'Automatically rebase the next PR in a GHerrit stack.'
inputs:
  token:
    description: 'GitHub API token used to authenticate PR updates and Git publication'
    required: true
  pr_body:
    description: 'The body/description of the PR that was just merged. Used to authenticate the GHerrit stack relationship.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        GHERRIT_TOKEN: ${{ inputs.token }}
        MERGED_PR_BODY: ${{ inputs.pr_body }}
        MERGED_PR_NUMBER: ${{ github.event.pull_request.number }}
        MERGED_PR_HEAD: ${{ github.event.pull_request.head.ref }}
        MERGED_PR_BASE: ${{ github.event.pull_request.base.ref }}
        MERGED_HEAD_REPOSITORY_ID: ${{ github.event.pull_request.head.repo.node_id }}
        MERGED_BASE_REPOSITORY_ID: ${{ github.event.pull_request.base.repo.node_id }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        TARGET_REPOSITORY: ${{ github.repository }}
        TARGET_REPOSITORY_ID: ${{ github.event.repository.node_id }}
      run: bash "$ACTION_PATH/ci/cascade_stack.sh"
