#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from typing import NoReturn

METADATA_PREFIX = "<!-- gherrit-meta: "
METADATA_SUFFIX = " -->"
TRAILER_TOKEN = "gherrit-pr-id"
CURRENT_ID = re.compile(r"^G[a-z2-7]{32}$")
LEGACY_ID = re.compile(r"^[GI][0-9a-f]{40}$")
GENERATED_BODY_WARNING = "<!-- WARNING: This PR description is automatically generated by GHerrit. Any manual edits will be overwritten on the next push. -->"
NAVIGATION_MARKER = "\n\n---\n\n"
DOWNLOAD_MARKER = "\n<details>\n<summary><strong>⬇️ Download this PR</strong></summary>"
HISTORY_MARKER = "\n\n**Latest Update:**"
FOOTER = "\n\n*Stacked PRs enabled by [GHerrit](https://github.com/joshlf/gherrit).*"
METADATA_WARNING = "<!-- WARNING: GHerrit relies on the following metadata to work properly. DO NOT EDIT OR REMOVE. -->"
PROVISIONAL_STATUS = "\n\n---\n\n*GHerrit is completing the initial projection for this PR.*"
# GitHub rejects PR bodies above 65,536 characters. A lower UTF-8 byte cap
# leaves room for API-side representation differences and fails conservatively.
MAX_PROMOTED_BODY_BYTES = 60_000
MAX_HISTORY_ROWS = 32


def fail(message: str) -> NoReturn:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def valid_id(value: object) -> bool:
    return isinstance(value, str) and bool(
        CURRENT_ID.fullmatch(value) or LEGACY_ID.fullmatch(value)
    )


def validate_id(value: str, context: str = "GHerrit ID") -> str:
    if not valid_id(value):
        fail(f"{context} is not a supported GHerrit ID.")
    return value


def parse_metadata(body: str) -> tuple[dict[str, str | None], int]:
    body = body.rstrip()
    start = body.rfind(METADATA_PREFIX)
    if start < 0:
        fail("Could not find terminal GHerrit metadata in the PR body.")

    candidate = body[start:]
    if not candidate.endswith(METADATA_SUFFIX) or start + len(candidate) != len(body):
        fail("GHerrit metadata comment is not terminal.")

    payload = candidate[len(METADATA_PREFIX) : -len(METADATA_SUFFIX)]
    try:
        metadata = json.loads(payload)
    except json.JSONDecodeError as primary:
        if not payload.endswith('"'):
            fail(f"GHerrit metadata is not valid JSON: {primary}")
        try:
            metadata = json.loads(payload[:-1])
        except json.JSONDecodeError:
            fail(f"GHerrit metadata is not valid JSON: {primary}")

    if not isinstance(metadata, dict) or set(metadata) != {"id", "parent", "child"}:
        fail("GHerrit metadata must contain exactly id, parent, and child.")

    for field in ("id", "parent", "child"):
        value = metadata[field]
        if field == "id":
            valid_type = isinstance(value, str)
        else:
            valid_type = value is None or isinstance(value, str)
        if not valid_type:
            fail(f"GHerrit metadata field {field} has the wrong type.")
        if isinstance(value, str) and not valid_id(value):
            fail(f"GHerrit metadata field {field} is not a supported GHerrit ID.")

    if metadata["parent"] == metadata["id"]:
        fail("GHerrit metadata names its own ID as its parent.")
    if metadata["child"] == metadata["id"]:
        fail("GHerrit metadata names its own ID as its child.")

    return metadata, start


def render_metadata(metadata: dict[str, str | None]) -> str:
    ordered = {
        "id": metadata["id"],
        "parent": metadata["parent"],
        "child": metadata["child"],
    }
    return (
        METADATA_PREFIX
        + json.dumps(ordered, separators=(",", ":"), ensure_ascii=False)
        + METADATA_SUFFIX
    )


def command_metadata(_: argparse.Namespace) -> None:
    metadata, _ = parse_metadata(sys.stdin.read())
    print(json.dumps(metadata, sort_keys=True, separators=(",", ":")))


def command_trailer_id(_: argparse.Namespace) -> None:
    ids: list[str] = []
    for line in sys.stdin.read().splitlines():
        token, separator, value = line.partition(":")
        if separator and token.strip().casefold() == TRAILER_TOKEN:
            ids.append(value.strip())
    if len(ids) != 1:
        fail("Commit does not carry exactly one gherrit-pr-id trailer.")
    print(validate_id(ids[0], "Commit gherrit-pr-id trailer"))


def history_section(
    *, gherrit_id: str, latest: int, repo_url: str, base_branch: str
) -> str:
    if latest <= 1:
        return ""

    lines = [
        f"\n\n**Latest Update:** v{latest} — [Compare vs v{latest - 1}]({repo_url}/compare/gherrit/{gherrit_id}/v{latest - 1}..gherrit/{gherrit_id}/v{latest})\n",
        "<details>",
        "<summary><strong>📚 Full Patch History</strong></summary>",
        "",
    ]
    if latest <= 8:
        lines.extend(
            [
                "*Links show the diff between the row version and the column version.*",
                "",
            ]
        )
        versions = list(range(latest - 1, 0, -1))
        lines.append(
            "|Version|" + "".join(f" v{version} |" for version in versions) + "Base|"
        )
        lines.append("|:---|" + ":---|" * len(versions) + ":---|")
        for row in range(latest, 0, -1):
            cells = [f"|v{row}|"]
            for column in versions:
                if column >= row:
                    cells.append("|")
                else:
                    cells.append(
                        f"[vs v{column}]({repo_url}/compare/gherrit/{gherrit_id}/v{column}..gherrit/{gherrit_id}/v{row})|"
                    )
            cells.append(
                f"[vs Base]({repo_url}/compare/{base_branch}..gherrit/{gherrit_id}/v{row})|"
            )
            lines.append("".join(cells))
    else:
        oldest = max(1, latest - MAX_HISTORY_ROWS + 1)
        lines.extend(
            [
                "*Each row compares that version with its predecessor and the current base.*",
                "",
                "|Version|Previous version|Base|",
                "|:---|:---|:---|",
            ]
        )
        for version in range(latest, oldest - 1, -1):
            previous = (
                f"[v{version - 1}]({repo_url}/compare/gherrit/{gherrit_id}/v{version - 1}..gherrit/{gherrit_id}/v{version})"
                if version > 1
                else "—"
            )
            base = f"[Base]({repo_url}/compare/{base_branch}..gherrit/{gherrit_id}/v{version})"
            lines.append(f"|v{version}|{previous}|{base}|")
        if oldest > 1:
            lines.extend(
                [
                    "",
                    f"*Showing the latest {MAX_HISTORY_ROWS} of {latest} patch versions; older version tags remain available in Git.*",
                ]
            )
    lines.extend(["", "</details>"])
    return "\n".join(lines)


def navigation_section(
    *, gherrit_id: str, child: str | None, repo_url: str, base_branch: str
) -> str:
    lines: list[str] = []
    if child is not None:
        lines.append(
            f"- 　  [Next]({repo_url}/compare/{gherrit_id}..{child}) (`{child}`)"
        )
    lines.append(
        f"- 👉 [Current]({repo_url}/compare/{base_branch}..{gherrit_id}) (`{gherrit_id}`)"
    )
    return "\n".join(lines)


def download_section(*, gherrit_id: str, latest: int, repo_url: str) -> str:
    del latest, repo_url
    fetch = f"git fetch origin refs/heads/{gherrit_id}"
    return "\n".join(
        [
            "<details>",
            "<summary><strong>⬇️ Download this PR</strong></summary>",
            "",
            "######",
            "",
            "**Branch**",
            "```bash",
            f"{fetch} && git checkout -b pr-{gherrit_id} FETCH_HEAD",
            "```",
            "",
            "**Checkout**",
            "```bash",
            f"{fetch} && git checkout FETCH_HEAD",
            "```",
            "",
            "**Cherry Pick**",
            "```bash",
            f"{fetch} && git cherry-pick FETCH_HEAD",
            "```",
            "",
            "**Pull**",
            "```bash",
            f"git pull origin refs/heads/{gherrit_id}",
            "```",
            "",
            "</details>",
        ]
    )


def provisional_user_body(prefix: str) -> str | None:
    suffix = PROVISIONAL_STATUS + "\n\n" + METADATA_WARNING
    if not prefix.endswith(suffix):
        return None
    prefix = prefix[: -len(suffix)]
    marker = GENERATED_BODY_WARNING + "\n\n"
    if not prefix.startswith(marker):
        return None
    return prefix[len(marker) :].rstrip()


def full_promoted_body(
    *,
    user_body: str,
    metadata: dict[str, str | None],
    gherrit_id: str,
    latest: int,
    repo_url: str,
    base_branch: str,
) -> str:
    generated = navigation_section(
        gherrit_id=gherrit_id,
        child=metadata["child"],
        repo_url=repo_url,
        base_branch=base_branch,
    )
    generated += history_section(
        gherrit_id=gherrit_id,
        latest=latest,
        repo_url=repo_url,
        base_branch=base_branch,
    )
    generated += "\n" + download_section(
        gherrit_id=gherrit_id, latest=latest, repo_url=repo_url
    )
    prefix = GENERATED_BODY_WARNING + "\n\n" + user_body.rstrip()
    prefix += NAVIGATION_MARKER + generated + FOOTER
    return prefix + "\n\n" + METADATA_WARNING + render_metadata(metadata)


def emit_promoted_body(body: str) -> None:
    size = len(body.encode("utf-8"))
    if size > MAX_PROMOTED_BODY_BYTES:
        fail(
            f"Promoted PR body is {size} bytes, exceeding GHerrit's conservative {MAX_PROMOTED_BODY_BYTES}-byte limit. Shorten the user-authored body before cascading."
        )
    print(body, end="")


def command_promote_body(args: argparse.Namespace) -> None:
    body = sys.stdin.read().rstrip()
    metadata, metadata_start = parse_metadata(body)
    validate_id(args.id)
    validate_id(args.parent)
    if metadata["id"] != args.id:
        fail("Child PR metadata ID does not match the requested GHerrit ID.")
    if metadata["parent"] not in (args.parent, None):
        fail("Child PR metadata names an unexpected parent.")
    if args.latest < 1:
        fail("Latest patch version must be positive.")

    repo_url = args.repo_url.rstrip("/")
    prefix = body[:metadata_start].rstrip()
    metadata["parent"] = None

    user_body = provisional_user_body(prefix)
    if user_body is not None:
        emit_promoted_body(
            full_promoted_body(
                user_body=user_body,
                metadata=metadata,
                gherrit_id=args.id,
                latest=args.latest,
                repo_url=repo_url,
                base_branch=args.base,
            )
        )
        return

    terminal_suffix = FOOTER + "\n\n" + METADATA_WARNING
    if not prefix.endswith(terminal_suffix):
        fail("Generated GHerrit sections do not have the authenticated terminal suffix.")
    generated_body = prefix[: -len(terminal_suffix)]

    # Authenticate only the final generated tail. Marker-like prose or fenced
    # examples in the user-authored prefix must never be treated as structure.
    navigation = generated_body.rfind(NAVIGATION_MARKER)
    if navigation < 0:
        fail("Could not find the terminal generated stack-navigation section.")
    generated_tail = generated_body[navigation + len(NAVIGATION_MARKER) :]
    if generated_tail.count(DOWNLOAD_MARKER) != 1:
        fail("Generated GHerrit download section is missing or ambiguous.")
    if generated_tail.count(HISTORY_MARKER) > 1:
        fail("Generated GHerrit history section is ambiguous.")

    download = generated_tail.rfind(DOWNLOAD_MARKER)
    history = generated_tail.rfind(HISTORY_MARKER)
    if history >= 0:
        if history > download:
            fail("Existing GHerrit history section is malformed.")
    if not generated_tail[download:].endswith("</details>"):
        fail("Generated GHerrit download section has an unexpected suffix.")

    generated = navigation_section(
        gherrit_id=args.id,
        child=metadata["child"],
        repo_url=repo_url,
        base_branch=args.base,
    )
    generated += history_section(
        gherrit_id=args.id,
        latest=args.latest,
        repo_url=repo_url,
        base_branch=args.base,
    )
    generated += "\n" + download_section(
        gherrit_id=args.id, latest=args.latest, repo_url=repo_url
    )

    promoted = (
        generated_body[:navigation]
        + NAVIGATION_MARKER
        + generated
        + terminal_suffix
        + render_metadata(metadata)
    )
    emit_promoted_body(promoted)


def require_mapping(value: object, context: str) -> dict[str, object]:
    if not isinstance(value, dict):
        fail(f"{context} is not an object.")
    return value


def command_base_consumer(args: argparse.Namespace) -> None:
    validate_id(args.child, "Rewritten child branch")
    grandchild = args.grandchild or None
    if grandchild is not None:
        validate_id(grandchild, "Expected grandchild branch")

    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError as error:
        fail(f"Base-consumer lookup is not valid JSON: {error}")
    root = require_mapping(payload, "Base-consumer lookup")
    data = require_mapping(root.get("data"), "Base-consumer lookup data")
    repository = require_mapping(data.get("repository"), "Base-consumer repository")
    if repository.get("id") != args.repository:
        fail("Base-consumer lookup repository identity changed.")
    connection = require_mapping(
        repository.get("pullRequests"), "Base-consumer connection"
    )
    total = connection.get("totalCount")
    nodes = connection.get("nodes")
    if not isinstance(total, int) or total < 0 or not isinstance(nodes, list):
        fail("Base-consumer connection has invalid pagination metadata.")
    if total != len(nodes):
        fail(
            f"Base-consumer lookup returned only {len(nodes)} of {total} candidates; refusing an unpaginated selection."
        )

    if grandchild is None:
        if nodes:
            fail(
                f"Open pull requests target rewritten branch '{args.child}', but its authenticated metadata names no grandchild."
            )
        print("null")
        return
    if len(nodes) != 1:
        fail(
            f"Expected exactly one authenticated open grandchild PR targeting '{args.child}', found {len(nodes)}."
        )

    candidate = require_mapping(nodes[0], "Base-consumer candidate")
    head_repository = require_mapping(
        candidate.get("headRepository"), "Base-consumer head repository"
    )
    base_repository = require_mapping(
        candidate.get("baseRepository"), "Base-consumer base repository"
    )
    if (
        candidate.get("headRefName") != grandchild
        or candidate.get("baseRefName") != args.child
        or candidate.get("isCrossRepository") is not False
        or head_repository.get("id") != args.repository
        or base_repository.get("id") != args.repository
    ):
        fail("Open base consumer is not the authenticated same-repository grandchild.")
    if candidate.get("isInMergeQueue") is True:
        fail("Grandchild PR is in the merge queue; refusing to rewrite its base branch.")
    if candidate.get("autoMergeRequest") is not None:
        fail("Grandchild PR has auto-merge enabled; refusing to rewrite its base branch.")
    if candidate.get("stackEntry") is not None:
        fail("Grandchild PR belongs to a native GitHub stack; refusing to rewrite its base branch.")

    body = candidate.get("body")
    if not isinstance(body, str):
        fail("Grandchild PR body is unavailable.")
    metadata, _ = parse_metadata(body)
    if metadata["id"] != grandchild or metadata["parent"] != args.child:
        fail("Grandchild PR terminal metadata does not authenticate the rewritten child.")

    number = candidate.get("number")
    node_id = candidate.get("id")
    head_oid = candidate.get("headRefOid")
    base_oid = candidate.get("baseRefOid")
    if (
        not isinstance(number, int)
        or not isinstance(node_id, str)
        or not node_id
        or not isinstance(head_oid, str)
        or not head_oid
        or not isinstance(base_oid, str)
        or not base_oid
    ):
        fail("Grandchild PR identity, head OID, or associated base OID is unavailable.")
    print(
        json.dumps(
            {
                "number": number,
                "nodeId": node_id,
                "headRefName": grandchild,
                "headRefOid": head_oid,
                "baseRefOid": base_oid,
            },
            separators=(",", ":"),
        )
    )


@dataclass
class TagObservation:
    direct: str | None = None
    peeled: str | None = None


def parse_version_observations(
    gherrit_id: str, lines: str
) -> dict[int, TagObservation]:
    validate_id(gherrit_id)
    observations: dict[int, TagObservation] = {}
    prefix = f"refs/tags/gherrit/{gherrit_id}/v"
    for line in lines.splitlines():
        try:
            oid, refname = line.split("\t", 1)
        except ValueError:
            continue
        peeled = refname.endswith("^{}")
        if peeled:
            refname = refname[:-3]
        if not refname.startswith(prefix):
            continue
        suffix = refname[len(prefix) :]
        if not suffix or not suffix.isascii() or not suffix.isdecimal():
            fail(f"Remote patch tag '{refname}' has a noncanonical version number.")
        version = int(suffix)
        if version < 1 or suffix != str(version):
            fail(f"Remote patch tag '{refname}' has a noncanonical version number.")
        observation = observations.setdefault(version, TagObservation())
        field = "peeled" if peeled else "direct"
        existing = getattr(observation, field)
        if existing is not None and existing != oid:
            fail(f"Remote patch tag '{refname}' was reported with conflicting object IDs.")
        setattr(observation, field, oid)

    if not observations:
        fail(f"Managed branch {gherrit_id} has no authoritative GHerrit patch-version tag.")
    latest = max(observations)
    for version in range(1, latest + 1):
        if version not in observations:
            fail(
                f"Remote patch history for GHerrit ID '{gherrit_id}' is missing authoritative version v{version} before v{latest}."
            )
        if observations[version].direct is None:
            fail(f"Remote patch tag gherrit/{gherrit_id}/v{version} has no tag ref object.")
    return observations


def tag_target(observation: TagObservation) -> str:
    return observation.peeled or observation.direct or fail(
        "Remote patch tag has no target object."
    )


def command_version_state(args: argparse.Namespace) -> None:
    observations = parse_version_observations(args.id, sys.stdin.read())
    latest = max(observations)
    target = tag_target(observations[latest])
    if target != args.expected_head:
        fail(
            f"Remote patch tag gherrit/{args.id}/v{latest} points to {target}, but managed branch {args.id} points to {args.expected_head}."
        )
    print(json.dumps({"latest": latest, "target": target, "next": latest + 1}, separators=(",", ":")))


def command_authenticate_version(args: argparse.Namespace) -> None:
    observations = parse_version_observations(args.id, sys.stdin.read())
    matching = [
        version
        for version, observation in observations.items()
        if tag_target(observation) == args.expected_target
    ]
    if not matching:
        fail(
            f"Commit {args.expected_target} is not authenticated by any authoritative patch-version tag for GHerrit ID '{args.id}'."
        )
    print(max(matching))


def main() -> None:
    parser = argparse.ArgumentParser()
    commands = parser.add_subparsers(dest="command", required=True)

    metadata = commands.add_parser("metadata")
    metadata.set_defaults(function=command_metadata)

    trailer = commands.add_parser("trailer-id")
    trailer.set_defaults(function=command_trailer_id)

    promote = commands.add_parser("promote-body")
    promote.add_argument("--id", required=True)
    promote.add_argument("--parent", required=True)
    promote.add_argument("--latest", type=int, required=True)
    promote.add_argument("--repo-url", required=True)
    promote.add_argument("--base", required=True)
    promote.set_defaults(function=command_promote_body)

    consumer = commands.add_parser("base-consumer")
    consumer.add_argument("--child", required=True)
    consumer.add_argument("--grandchild", default="")
    consumer.add_argument("--repository", required=True)
    consumer.set_defaults(function=command_base_consumer)

    versions = commands.add_parser("version-state")
    versions.add_argument("--id", required=True)
    versions.add_argument("--expected-head", required=True)
    versions.set_defaults(function=command_version_state)

    authenticate = commands.add_parser("authenticate-version")
    authenticate.add_argument("--id", required=True)
    authenticate.add_argument("--expected-target", required=True)
    authenticate.set_defaults(function=command_authenticate_version)

    args = parser.parse_args()
    args.function(args)


if __name__ == "__main__":
    main()
