#!/usr/bin/env bash

set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
root=$(mktemp -d)
trap 'rm -rf "$root"' EXIT
real_git=$(command -v git)
repository_id=R_target_repository
repository_name=owner/repository

current_a=Gbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
current_b=Gaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
current_c=Gcccccccccccccccccccccccccccccccc
legacy_g=G0123456789abcdef0123456789abcdef01234567
legacy_i=I0123456789abcdef0123456789abcdef01234567

body_for() {
  local id=$1 parent=$2 child=$3
  local parent_json child_json
  if [[ -n $parent ]]; then parent_json=\"$parent\"; else parent_json=null; fi
  if [[ -n $child ]]; then child_json=\"$child\"; else child_json=null; fi
  cat <<EOF
<!-- WARNING: This PR description is automatically generated by GHerrit. Any manual edits will be overwritten on the next push. -->

Test PR body.

---

- 👉 #1

<details>
<summary><strong>⬇️ Download this PR</strong></summary>

######

</details>

*Stacked PRs enabled by [GHerrit](https://github.com/joshlf/gherrit).*

<!-- WARNING: GHerrit relies on the following metadata to work properly. DO NOT EDIT OR REMOVE. --><!-- gherrit-meta: {"id":"$id","parent":$parent_json,"child":$child_json} -->
EOF
}

provisional_body_for() {
  local id=$1 parent=$2 child=$3 user_body=${4:-Test provisional body.}
  local parent_json child_json
  if [[ -n $parent ]]; then parent_json=\"$parent\"; else parent_json=null; fi
  if [[ -n $child ]]; then child_json=\"$child\"; else child_json=null; fi
  cat <<EOF
<!-- WARNING: This PR description is automatically generated by GHerrit. Any manual edits will be overwritten on the next push. -->

$user_body

---

*GHerrit is completing the initial projection for this PR.*

<!-- WARNING: GHerrit relies on the following metadata to work properly. DO NOT EDIT OR REMOVE. --><!-- gherrit-meta: {"id":"$id","parent":$parent_json,"child":$child_json} -->
EOF
}

write_fake_tools() {
  local bin=$1
  mkdir -p "$bin"
  cat > "$bin/gh" <<'GH'
#!/usr/bin/env bash
set -euo pipefail

get_arg() {
  local key=$1; shift
  local previous=
  for value in "$@"; do
    if [[ $previous == "$key" ]]; then printf '%s' "$value"; return 0; fi
    previous=$value
  done
  return 1
}

if [[ ${1:-} == api && ${2:-} == graphql ]]; then
  joined=$*
  if [[ $joined == *'mergedPr: pullRequest'* ]]; then
    number=$(get_arg -F "$@" | sed -n 's/^number=//p')
    if [[ -z $number ]]; then number=$(get_arg -f "$@" | sed -n 's/^number=//p'); fi
    pr=$(jq -ce --argjson number "$number" '.prs[] | select(.number == $number)' "$TEST_STATE")
    merged_head=$(jq -er '.head' <<<"$pr")
    if "$REAL_GIT" --git-dir="$TEST_REMOTE" show-ref --verify --quiet "refs/heads/$merged_head"; then
      merged_head_oid=$("$REAL_GIT" --git-dir="$TEST_REMOTE" rev-parse "refs/heads/$merged_head")
    else
      merged_head_oid=$(jq -er '.head_oid' <<<"$pr")
    fi
    jq -cn \
      --arg repository "$TARGET_REPOSITORY_ID" \
      --arg default "$DEFAULT_BRANCH" \
      --arg head_oid "$merged_head_oid" \
      --argjson pr "$pr" '
        {data: {repository: {
          id: $repository,
          defaultBranchRef: {name: $default},
          mergedPr: {
            number: $pr.number,
            body: $pr.body,
            merged: $pr.merged,
            headRefName: $pr.head,
            headRefOid: $head_oid,
            baseRefName: $pr.base,
            isCrossRepository: false,
            headRepository: {id: $repository},
            baseRepository: {id: $repository}
          }
        }}}
      '
  elif [[ $joined == *'pullRequests(baseRefName: $base'* ]]; then
    base_arg=
    previous=
    for value in "$@"; do
      if [[ $previous == -f && $value == base=* ]]; then base_arg=${value#base=}; fi
      previous=$value
    done
    nodes=$(jq -c --arg base "$base_arg" --arg repository "$TARGET_REPOSITORY_ID" '
      [.prs[] | select(.base == $base and .merged == false) | {
        id: .id,
        number: .number,
        body: .body,
        headRefName: .head,
        headRefOid: .head_oid,
        baseRefName: .base,
        isCrossRepository: (.cross // false),
        isInMergeQueue: .queue,
        autoMergeRequest: (if .auto then {enabledAt: "now"} else null end),
        stackEntry: (if .stack then {id: "stack"} else null end),
        headRepository: (if (.head_repository_unknown // false) then null else {id: (.head_repository_id // $repository)} end),
        baseRepository: (if (.base_repository_unknown // false) then null else {id: (.base_repository_id // $repository)} end)
      }]
    ' "$TEST_STATE")
    count=$(jq 'length' <<<"$nodes")
    jq -cn \
      --arg repository "$TARGET_REPOSITORY_ID" \
      --argjson count "$count" \
      --argjson nodes "$nodes" '
        {data: {repository: {
          id: $repository,
          pullRequests: {totalCount: $count, nodes: $nodes}
        }}}
      '
  elif [[ $joined == *'parentRef: ref'* ]]; then
    head_arg=
    parent_ref=
    previous=
    for value in "$@"; do
      if [[ $previous == -f && $value == head=* ]]; then head_arg=${value#head=}; fi
      if [[ $previous == -f && $value == parentRef=* ]]; then parent_ref=${value#parentRef=}; fi
      previous=$value
    done
    parent_name=${parent_ref#refs/heads/}
    if "$REAL_GIT" --git-dir="$TEST_REMOTE" show-ref --verify --quiet "refs/heads/$parent_name"; then
      parent_json='{"id":"REF"}'
    else
      parent_json=null
    fi
    current_head_oid=$("$REAL_GIT" --git-dir="$TEST_REMOTE" rev-parse "refs/heads/$head_arg")
    nodes=$(jq -c --arg head "$head_arg" --arg oid "$current_head_oid" --arg repository "$TARGET_REPOSITORY_ID" '
      [.prs[] | select(.head == $head and .merged == false) | {
        id: .id,
        number: .number,
        body: .body,
        headRefName: .head,
        headRefOid: $oid,
        baseRefName: .base,
        isCrossRepository: false,
        isInMergeQueue: .queue,
        autoMergeRequest: (if .auto then {enabledAt: "now"} else null end),
        stackEntry: (if .stack then {id: "stack"} else null end),
        headRepository: {id: $repository},
        baseRepository: {id: $repository}
      }]
    ' "$TEST_STATE")
    count=$(jq 'length' <<<"$nodes")
    jq -cn \
      --arg repository "$TARGET_REPOSITORY_ID" \
      --argjson parent "$parent_json" \
      --argjson count "$count" \
      --argjson nodes "$nodes" '
        {data: {repository: {
          id: $repository,
          parentRef: $parent,
          pullRequests: {totalCount: $count, nodes: $nodes}
        }}}
      '
  elif [[ $joined == *'updatePullRequest'* ]]; then
    pr_id= base= body=
    previous=
    for value in "$@"; do
      if [[ $previous == -f && $value == prId=* ]]; then pr_id=${value#prId=}; fi
      if [[ $previous == -f && $value == base=* ]]; then base=${value#base=}; fi
      if [[ $previous == -f && $value == body=* ]]; then body=${value#body=}; fi
      previous=$value
    done
    if [[ ${TEST_UPDATE_MODE:-none} == before ]]; then
      echo 'injected update failure before application' >&2
      exit 1
    fi
    tmp=$TEST_STATE.tmp
    jq --arg id "$pr_id" --arg base "$base" --arg body "$body" '
      .prs |= map(if .id == $id then .base = $base | .body = $body else . end)
    ' "$TEST_STATE" > "$tmp"
    mv "$tmp" "$TEST_STATE"
    if [[ ${TEST_UPDATE_MODE:-none} == after ]]; then
      echo 'injected update failure after application' >&2
      exit 1
    fi
    jq -cn --arg id "$pr_id" '{data:{updatePullRequest:{pullRequest:{id:$id,number:42}}}}'
  else
    echo "unexpected GraphQL query" >&2
    exit 1
  fi
elif [[ ${1:-} == pr && ${2:-} == checkout ]]; then
  number=${3:?missing PR number}
  head=$(jq -er --argjson number "$number" '.prs[] | select(.number == $number) | .head' "$TEST_STATE")
  "$REAL_GIT" fetch --no-tags origin "refs/heads/$head" >/dev/null
  "$REAL_GIT" checkout -B "$head" FETCH_HEAD >/dev/null
else
  echo "unexpected gh invocation: $*" >&2
  exit 1
fi
GH
  chmod +x "$bin/gh"

  cat > "$bin/git" <<'GIT'
#!/usr/bin/env bash
set -euo pipefail
if [[ ${1:-} == push && ${TEST_PUSH_MODE:-none} == before ]]; then
  echo 'injected push failure before application' >&2
  exit 1
fi
if [[ ${1:-} == push && ${TEST_PUSH_MODE:-none} == after ]]; then
  "$REAL_GIT" "$@"
  echo 'injected push status loss after application' >&2
  exit 1
fi
exec "$REAL_GIT" "$@"
GIT
  chmod +x "$bin/git"
}

setup_repository() {
  local case_dir=$1; shift
  local remote=$case_dir/remote.git work=$case_dir/work
  mkdir -p "$case_dir"
  "$real_git" init --bare --initial-branch=main "$remote" >/dev/null
  "$real_git" clone "$remote" "$work" >/dev/null 2>&1
  (
    cd "$work"
    "$real_git" config user.name test
    "$real_git" config user.email test@example.com
    echo base > base.txt
    "$real_git" add base.txt
    "$real_git" commit -m base >/dev/null
    "$real_git" push -u origin main >/dev/null

    local previous=main index=0 id token
    for id in "$@"; do
      index=$((index + 1))
      "$real_git" checkout -b "$id" "$previous" >/dev/null
      echo "$id" > "change-$index.txt"
      "$real_git" add "change-$index.txt"
      token=gherrit-pr-id
      if [[ $id == "$legacy_g" ]]; then token=GHERRIT-PR-ID; fi
      if [[ $id == "$legacy_i" ]]; then token=GhErRiT-Pr-Id; fi
      "$real_git" commit -m "change $index" -m "$token: $id" >/dev/null
      "$real_git" tag "gherrit/$id/v1"
      "$real_git" push origin "$id" "refs/tags/gherrit/$id/v1" >/dev/null
      previous=$id
    done
  )
}

initialize_state() {
  local work=$1 state=$2; shift 2
  local ids=("$@")
  printf '{"prs":[' > "$state"
  local index id parent child comma= number
  for ((index=0; index<${#ids[@]}; index++)); do
    id=${ids[$index]}
    parent=
    child=
    (( index > 0 )) && parent=${ids[$((index - 1))]}
    (( index + 1 < ${#ids[@]} )) && child=${ids[$((index + 1))]}
    body=$(body_for "$id" "$parent" "$child")
    head_oid=$("$real_git" -C "$work" rev-parse "$id")
    number=$((index + 1))
    printf '%s' "$comma" >> "$state"
    jq -cn \
      --arg id "PR_$number" --argjson number "$number" \
      --arg head "$id" --arg head_oid "$head_oid" \
      --arg base "${parent:-main}" --arg body "$body" \
      '{id:$id,number:$number,head:$head,head_oid:$head_oid,base:$base,body:$body,merged:false,queue:false,auto:false,stack:false}' \
      >> "$state"
    comma=,
  done
  printf ']}' >> "$state"
}

merge_equivalent() {
  local work=$1 id=$2 shape=$3
  (
    cd "$work"
    "$real_git" checkout main >/dev/null
    "$real_git" fetch origin main >/dev/null
    "$real_git" reset --hard origin/main >/dev/null
    case "$shape" in
      squash)
        "$real_git" merge --squash "$id" >/dev/null
        "$real_git" commit -m "squash $id" >/dev/null
        ;;
      rebase)
        "$real_git" cherry-pick --no-commit "$id" >/dev/null
        "$real_git" commit -m "rebase-merged $id" >/dev/null
        ;;
      fast-forward)
        "$real_git" merge --ff-only "$id" >/dev/null
        ;;
      *) echo "unknown merge shape '$shape'" >&2; return 1 ;;
    esac
    "$real_git" push origin main >/dev/null
  )
}

mark_merged() {
  local state=$1 id=$2
  local body
  body=$(jq -er --arg id "$id" '.prs[] | select(.head == $id) | .body' "$state")
  tmp=$state.tmp
  jq --arg id "$id" '.prs |= map(if .head == $id then .merged = true | .base = "main" else . end)' "$state" > "$tmp"
  mv "$tmp" "$state"
  printf '%s' "$body"
}

run_action() {
  local work=$1 state=$2 merged_id=$3 merged_number=$4 merged_body=$5
  (
    cd "$work"
    export REAL_GIT="$real_git"
    export PATH="$TEST_BIN:$PATH"
    export ACTION_PATH="$repo_root"
    export GH_TOKEN=test-token
    export MERGED_PR_BODY="$merged_body"
    export MERGED_PR_NUMBER="$merged_number"
    export MERGED_PR_HEAD="$merged_id"
    export MERGED_PR_BASE=main
    export MERGED_HEAD_REPOSITORY_ID="$repository_id"
    export MERGED_BASE_REPOSITORY_ID="$repository_id"
    export DEFAULT_BRANCH=main
    export TARGET_REPOSITORY="$repository_name"
    export TARGET_REPOSITORY_ID="$repository_id"
    export TEST_STATE="$state"
    export TEST_REMOTE="$TEST_REMOTE"
    bash "$repo_root/ci/cascade_stack.sh"
  )
}

assert_promoted() {
  local remote=$1 state=$2 id=$3 expected_version=$4
  local head main body
  head=$("$real_git" --git-dir="$remote" rev-parse "refs/heads/$id")
  main=$("$real_git" --git-dir="$remote" rev-parse refs/heads/main)
  if [[ $head == "$main" ]]; then
    echo "promoted child '$id' equals the default branch" >&2
    exit 1
  fi
  if [[ $("$real_git" --git-dir="$remote" rev-parse "$head^") != "$main" ]]; then
    echo "promoted child '$id' is not directly based on main" >&2
    exit 1
  fi
  if [[ $("$real_git" --git-dir="$remote" rev-parse "refs/tags/gherrit/$id/v$expected_version") != "$head" ]]; then
    echo "promoted child '$id' lacks version v$expected_version at its head" >&2
    exit 1
  fi
  if [[ $(jq -er --arg id "$id" '.prs[] | select(.head == $id) | .base' "$state") != main ]]; then
    echo "promoted child '$id' did not target main" >&2
    exit 1
  fi
  body=$(jq -er --arg id "$id" '.prs[] | select(.head == $id) | .body' "$state")
  if [[ $(printf '%s' "$body" | bash "$repo_root/ci/extract_stack_metadata.sh" | jq -r '.parent // ""') != "" ]]; then
    echo "promoted child '$id' retained parent metadata" >&2
    exit 1
  fi
}

test_group=${CASCADE_TEST_GROUP:-all}
run_group() {
  [[ $test_group == all || $test_group == "$1" ]]
}

run_basic_case() {
  local shape=$1 parent_deleted=$2 child_id=${3:-$current_b}
  local case_dir=$root/basic-$shape-$parent_deleted-$child_id
  local remote=$case_dir/remote.git work=$case_dir/work state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$child_id"
  initialize_state "$work" "$state" "$current_a" "$child_id"
  merge_equivalent "$work" "$current_a" "$shape"
  merged_body=$(mark_merged "$state" "$current_a")
  if [[ $parent_deleted == true ]]; then "$real_git" --git-dir="$remote" update-ref -d "refs/heads/$current_a"; fi
  if [[ $parent_deleted == true ]]; then
    tmp=$state.tmp
    jq --arg id "$child_id" '.prs |= map(if .head == $id then .base = "main" else . end)' "$state" > "$tmp" && mv "$tmp" "$state"
  fi
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  run_action "$work" "$state" "$current_a" 1 "$merged_body"
  assert_promoted "$remote" "$state" "$child_id" 2
}

if run_group basic || run_group basic-parent; then
  run_basic_case squash false
fi
if run_group basic || run_group basic-auto; then
  run_basic_case squash true
fi
if run_group basic || run_group basic-rebase; then
  run_basic_case rebase true
fi
if run_group basic || run_group legacy; then
  run_basic_case squash false "$legacy_g"
  run_basic_case squash false "$legacy_i"
fi

# A three-PR stack must cascade twice. The first promotion rewrites B metadata
# to a root, and the second merged event can therefore authenticate B -> C.
if run_group two-hop; then
  case_dir=$root/two-hop
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b" "$current_c"
  initialize_state "$work" "$state" "$current_a" "$current_b" "$current_c"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  run_action "$work" "$state" "$current_a" 1 "$merged_body"
  assert_promoted "$remote" "$state" "$current_b" 2
  merge_equivalent "$work" "$current_b" squash
  merged_body=$(mark_merged "$state" "$current_b")
  run_action "$work" "$state" "$current_b" 2 "$merged_body"
  assert_promoted "$remote" "$state" "$current_c" 2
fi

# Rebase conflict and a pre-application push failure must leave the PR base and
# remote branch untouched while the parent ref is retained.
if run_group pre-publish-failures; then
  for failure in conflict push-before; do
    case_dir=$root/$failure
    remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
    setup_repository "$case_dir" "$current_a" "$current_b"
    initialize_state "$work" "$state" "$current_a" "$current_b"
    old_head=$("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b")
    if [[ $failure == conflict ]]; then
      (
        cd "$work"
        "$real_git" checkout main >/dev/null
        echo main > change-2.txt
        "$real_git" add change-2.txt
        "$real_git" commit -m conflicting-main >/dev/null
        "$real_git" push origin main >/dev/null
      )
    else
      merge_equivalent "$work" "$current_a" squash
    fi
    merged_body=$(mark_merged "$state" "$current_a")
    TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
    export TEST_BIN TEST_REMOTE TEST_UPDATE_MODE=none
    if [[ $failure == push-before ]]; then export TEST_PUSH_MODE=before; else export TEST_PUSH_MODE=none; fi
    write_fake_tools "$TEST_BIN"
    if run_action "$work" "$state" "$current_a" 1 "$merged_body" >/dev/null 2>&1; then
      echo "$failure cascade unexpectedly succeeded" >&2; exit 1
    fi
    [[ $(jq -er --arg id "$current_b" '.prs[] | select(.head == $id) | .base' "$state") == "$current_a" ]]
    [[ $("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b") == "$old_head" ]]
  done
fi

# Lost acknowledgements after the atomic push or PR update are reconciled by
# observing the exact durable result.
if run_group ambiguous-success; then
  for failure in push-after update-after; do
    case_dir=$root/$failure
    remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
    setup_repository "$case_dir" "$current_a" "$current_b"
    initialize_state "$work" "$state" "$current_a" "$current_b"
    merge_equivalent "$work" "$current_a" squash
    merged_body=$(mark_merged "$state" "$current_a")
    TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
    export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
    [[ $failure == push-after ]] && export TEST_PUSH_MODE=after
    [[ $failure == update-after ]] && export TEST_UPDATE_MODE=after
    write_fake_tools "$TEST_BIN"
    run_action "$work" "$state" "$current_a" 1 "$merged_body"
    assert_promoted "$remote" "$state" "$current_b" 2
  done
fi

# A lost/not-applied PR edit after successful Git publication is retryable even
# when the parent branch is retained.
if run_group projection-retry; then
  case_dir=$root/update-before
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=before
  write_fake_tools "$TEST_BIN"
  if run_action "$work" "$state" "$current_a" 1 "$merged_body" >/dev/null 2>&1; then
    echo "pre-application update failure unexpectedly succeeded" >&2; exit 1
  fi
  [[ $(jq -er --arg id "$current_b" '.prs[] | select(.head == $id) | .base' "$state") == "$current_a" ]]
  export TEST_UPDATE_MODE=none
  run_action "$work" "$state" "$current_a" 1 "$merged_body"
  assert_promoted "$remote" "$state" "$current_b" 2
fi

# A durable branch/version publication can be retried even if main advances
# before the failed projection is repaired. The retry rebases the authenticated
# child from the older main commit and allocates the next version.
if run_group projection-retry-advanced-default; then
  case_dir=$root/update-before-default-advance
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=before
  write_fake_tools "$TEST_BIN"
  if run_action "$work" "$state" "$current_a" 1 "$merged_body" >/dev/null 2>&1; then
    echo "pre-application update failure unexpectedly succeeded" >&2; exit 1
  fi
  [[ $("$real_git" --git-dir="$remote" rev-parse "refs/tags/gherrit/$current_b/v2") == \
     $("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b") ]]
  (
    cd "$work"
    "$real_git" checkout main >/dev/null
    "$real_git" fetch origin main >/dev/null
    "$real_git" reset --hard origin/main >/dev/null
    echo later > later-main.txt
    "$real_git" add later-main.txt
    "$real_git" commit -m later-main >/dev/null
    "$real_git" push origin main >/dev/null
  )
  export TEST_UPDATE_MODE=none
  run_action "$work" "$state" "$current_a" 1 "$merged_body"
  assert_promoted "$remote" "$state" "$current_b" 3
fi

# Provisional PR bodies are promoted into a complete generated envelope before
# the durable branch/version transaction is sent.
if run_group provisional-body; then
  case_dir=$root/provisional-body
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  provisional=$(provisional_body_for "$current_b" "$current_a" "")
  tmp=$state.tmp
  jq --arg id "$current_b" --arg body "$provisional" \
    '.prs |= map(if .head == $id then .body = $body else . end)' \
    "$state" > "$tmp" && mv "$tmp" "$state"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  run_action "$work" "$state" "$current_a" 1 "$merged_body"
  assert_promoted "$remote" "$state" "$current_b" 2
  promoted=$(jq -er --arg id "$current_b" '.prs[] | select(.head == $id) | .body' "$state")
  grep -Fq 'Test provisional body.' <<<"$promoted"
  grep -Fq '**Latest Update:** v2' <<<"$promoted"
  grep -Fq '<summary><strong>⬇️ Download this PR</strong></summary>' <<<"$promoted"
  if grep -Fq 'GHerrit is completing the initial projection for this PR' <<<"$promoted"; then
    echo "promoted provisional body retained its provisional status" >&2; exit 1
  fi
fi

# A body that has authenticated terminal metadata but no valid generated
# envelope must fail before the branch/version publication.
if run_group invalid-body-before-push; then
  case_dir=$root/invalid-body-before-push
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  malformed="User body without generated sections.

<!-- WARNING: GHerrit relies on the following metadata to work properly. DO NOT EDIT OR REMOVE. --><!-- gherrit-meta: {\"id\":\"$current_b\",\"parent\":\"$current_a\",\"child\":null} -->"
  tmp=$state.tmp
  jq --arg id "$current_b" --arg body "$malformed" \
    '.prs |= map(if .head == $id then .body = $body else . end)' \
    "$state" > "$tmp" && mv "$tmp" "$state"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  old_child=$("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  if run_action "$work" "$state" "$current_a" 1 "$merged_body" >/dev/null 2>&1; then
    echo "invalid body unexpectedly survived pre-publication promotion" >&2; exit 1
  fi
  [[ $("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b") == "$old_child" ]]
  if "$real_git" --git-dir="$remote" show-ref --verify --quiet \
    "refs/tags/gherrit/$current_b/v2"; then
    echo "invalid body was detected only after durable publication" >&2; exit 1
  fi
fi

# Marker-like user prose and fenced examples occur before the authenticated
# generated separator and must survive history regeneration unchanged.
if run_group user-body-markers; then
  case_dir=$root/user-body-markers
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  marker_body=$(body_for "$current_b" "$current_a" "")
  user_text='**Latest Update:** this is user-authored release prose.
KEEP-AFTER-PLAIN-HISTORY-MARKER

<details>
<summary><strong>⬇️ Download this PR</strong></summary>
This exact marker is ordinary user prose.
</details>
KEEP-AFTER-PLAIN-DOWNLOAD-MARKER

```markdown
**Latest Update:** this exact marker is inside a fenced example.
KEEP-AFTER-FENCED-HISTORY-MARKER

<details>
<summary><strong>⬇️ Download this PR</strong></summary>
</details>
```
KEEP-AFTER-FENCED-DOWNLOAD-MARKER'
  marker_body=${marker_body/Test PR body./$user_text}
  tmp=$state.tmp
  jq --arg id "$current_b" --arg body "$marker_body" \
    '.prs |= map(if .head == $id then .body = $body else . end)' \
    "$state" > "$tmp" && mv "$tmp" "$state"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  run_action "$work" "$state" "$current_a" 1 "$merged_body"
  promoted=$(jq -er --arg id "$current_b" '.prs[] | select(.head == $id) | .body' "$state")
  grep -Fq 'KEEP-AFTER-PLAIN-HISTORY-MARKER' <<<"$promoted"
  grep -Fq 'KEEP-AFTER-PLAIN-DOWNLOAD-MARKER' <<<"$promoted"
  grep -Fq 'KEEP-AFTER-FENCED-HISTORY-MARKER' <<<"$promoted"
  grep -Fq 'KEEP-AFTER-FENCED-DOWNLOAD-MARKER' <<<"$promoted"
  [[ $(grep -Fc '**Latest Update:**' <<<"$promoted") == 3 ]]
  [[ $(grep -Fc '<summary><strong>⬇️ Download this PR</strong></summary>' <<<"$promoted") == 3 ]]
fi

# Any unknown base consumer blocks the child-branch rewrite before publication.
# This head is not in the old child, but becomes reachable from the rebased child.
if run_group unrelated-base-consumer; then
  case_dir=$root/unrelated-base-consumer
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  merge_equivalent "$work" "$current_a" squash
  unrelated_head=$("$real_git" --git-dir="$remote" rev-parse refs/heads/main)
  "$real_git" --git-dir="$remote" update-ref refs/heads/unrelated "$unrelated_head"
  old_child=$("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b")
  if "$real_git" --git-dir="$remote" merge-base --is-ancestor "$unrelated_head" "$old_child"; then
    echo "unrelated test head unexpectedly starts inside the old child base" >&2; exit 1
  fi
  tmp=$state.tmp
  jq --arg oid "$unrelated_head" --arg base "$current_b" \
    '.prs += [{id:"PR_unrelated",number:99,head:"unrelated",head_oid:$oid,base:$base,body:"unrelated",merged:false,queue:false,auto:false,stack:false}]' \
    "$state" > "$tmp" && mv "$tmp" "$state"
  merged_body=$(mark_merged "$state" "$current_a")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  if run_action "$work" "$state" "$current_a" 1 "$merged_body" >/dev/null 2>&1; then
    echo "cascade with unrelated base consumer unexpectedly succeeded" >&2; exit 1
  fi
  [[ $("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b") == "$old_child" ]]
  if "$real_git" --git-dir="$remote" show-ref --verify --quiet \
    "refs/tags/gherrit/$current_b/v2"; then
    echo "cascade published v2 despite an unrelated base consumer" >&2; exit 1
  fi
fi

# The authenticated grandchild is affected by the rewritten child base, so its
# queue, auto-merge, and native-stack state are pre-publication blockers too.
run_grandchild_blocker_case() {
  local blocker=$1
  case_dir=$root/grandchild-blocker-$blocker
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b" "$current_c"
  initialize_state "$work" "$state" "$current_a" "$current_b" "$current_c"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  tmp=$state.tmp
  jq --arg id "$current_c" --arg blocker "$blocker" '
    .prs |= map(
      if .head == $id then
        .auto = ($blocker == "auto") |
        .queue = ($blocker == "queue") |
        .stack = ($blocker == "stack")
      else . end
    )
  ' "$state" > "$tmp" && mv "$tmp" "$state"
  old_child=$("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  if run_action "$work" "$state" "$current_a" 1 "$merged_body" >/dev/null 2>&1; then
    echo "$blocker grandchild blocker unexpectedly succeeded" >&2; exit 1
  fi
  [[ $("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b") == "$old_child" ]]
}

if run_group grandchild-blockers; then
  run_grandchild_blocker_case auto
  run_grandchild_blocker_case queue
  run_grandchild_blocker_case stack
fi

# Operational blockers are checked before checkout, rebase, push, or retarget.
run_blocker_case() {
  local blocker=$1
  case_dir=$root/blocker-$blocker
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  merge_equivalent "$work" "$current_a" squash
  merged_body=$(mark_merged "$state" "$current_a")
  tmp=$state.tmp
  jq --arg id "$current_b" --arg blocker "$blocker" '
    .prs |= map(
      if .head == $id then
        .auto = ($blocker == "auto") |
        .queue = ($blocker == "queue") |
        .stack = ($blocker == "stack")
      else . end
    )
  ' "$state" > "$tmp" && mv "$tmp" "$state"
  old_head=$("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  if run_action "$work" "$state" "$current_a" 1 "$merged_body" >/dev/null 2>&1; then
    echo "$blocker cascade unexpectedly succeeded" >&2; exit 1
  fi
  [[ $("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b") == "$old_head" ]]
  [[ $(jq -er --arg id "$current_b" '.prs[] | select(.head == $id) | .base' "$state") == "$current_a" ]]
}

if run_group blockers || run_group blocker-auto; then
  run_blocker_case auto
fi
if run_group blockers || run_group blocker-queue; then
  run_blocker_case queue
fi
if run_group blockers || run_group blocker-stack; then
  run_blocker_case stack
fi

# If the child patch is already represented upstream, --empty=keep must still
# preserve a distinct authenticated child commit rather than pushing main.
if run_group empty-child; then
  case_dir=$root/empty-child
  remote=$case_dir/remote.git; work=$case_dir/work; state=$case_dir/state.json
  setup_repository "$case_dir" "$current_a" "$current_b"
  initialize_state "$work" "$state" "$current_a" "$current_b"
  (
    cd "$work"
    "$real_git" checkout main >/dev/null
    "$real_git" cherry-pick --no-commit "$current_a" >/dev/null
    "$real_git" cherry-pick --no-commit "$current_b" >/dev/null
    "$real_git" commit -m 'land parent and child equivalents' >/dev/null
    "$real_git" push origin main >/dev/null
  )
  merged_body=$(mark_merged "$state" "$current_a")
  TEST_BIN=$case_dir/bin TEST_REMOTE=$remote
  export TEST_BIN TEST_REMOTE TEST_PUSH_MODE=none TEST_UPDATE_MODE=none
  write_fake_tools "$TEST_BIN"
  run_action "$work" "$state" "$current_a" 1 "$merged_body"
  assert_promoted "$remote" "$state" "$current_b" 2
  child_head=$("$real_git" --git-dir="$remote" rev-parse "refs/heads/$current_b")
  main_head=$("$real_git" --git-dir="$remote" rev-parse refs/heads/main)
  [[ $("$real_git" --git-dir="$remote" rev-parse "$child_head^{tree}") == $("$real_git" --git-dir="$remote" rev-parse "$main_head^{tree}") ]]
fi
